# Generated by Django 5.2 on 2025-05-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vending_machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=4, unique=True)),
                ('vending_machine_type', models.CharField(max_length=100)),
                ('no_of_items', models.IntegerField(db_default=0)),
            ],
        ),
        migrations.CreateModel(
            name='machine_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_cost', models.FloatField()),
                ('item_quantity', models.IntegerField()),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendingmachine.vending_machine')),
            ],
        ),
    ]
