# Generated by Django 5.2 on 2025-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingmachine', '0002_vending_machine_machine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vending_machine',
            name='machine_name',
            field=models.CharField(max_length=30),
        ),
    ]
