# Generated by Django 5.2 on 2025-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingmachine', '0003_alter_vending_machine_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vending_machine',
            name='no_of_items',
            field=models.PositiveIntegerField(db_default=0),
        ),
    ]
