# Generated by Django 5.2 on 2025-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingmachine', '0004_alter_vending_machine_no_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='vending_machine',
            name='items_to_be_added',
            field=models.PositiveBigIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='machine_item',
            name='item_quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
