# Generated by Django 5.2 on 2025-05-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingmachine', '0005_vending_machine_items_to_be_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vending_machine',
            name='items_to_be_added',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vending_machine',
            name='no_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
