# Generated by Django 5.2 on 2025-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingmachine', '0006_alter_vending_machine_items_to_be_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vending_machine',
            name='machine_name',
        ),
        migrations.AlterField(
            model_name='vending_machine',
            name='machine_id',
            field=models.IntegerField(unique=True),
        ),
    ]
